services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrongPassword123!
      - MSSQL_PID=Developer
    ports:
      - '1433:1433'
    volumes:
      - mssql:/var/opt/mssql
    networks:
      - virtual-network

  backend-gateway:
    image: ${DOCKER_REGISTRY-}backend-gateway
    build:
      context: ./BackendGateway
      dockerfile: Dockerfile
    ports:
      - '5000:80'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    networks:
      - virtual-network

  user-service:
    image: ${DOCKER_REGISTRY-}user-service
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - '5001:80'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    networks:
      - virtual-network

  authentication-service:
    image: ${DOCKER_REGISTRY-}authentication-service
    build:
      context: ./AuthenticationService
      dockerfile: Dockerfile
    ports:
      - '5053:80'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MyDb;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;Encrypt=False
    depends_on:
      - sqlserver
    networks:
      - virtual-network

networks:
  virtual-network:

volumes:
  mssql:
